"use client";

import type { LayerSpecification } from "maplibre-gl";
import { Layer, Source } from "react-map-gl/maplibre";
import type { ResolvedTheme } from "@/lib/use-resolved-theme";
// Generated by scripts/campus-map/style.mjs from FO's ArcGIS renderers.
import campusStyle from "../../../../public/campus-map/style.json";
import { SLOTS } from "../slots";
import { useMaxZoomReached } from "../use-map-zoom";

type CampusLayer = LayerSpecification & { source: string; minzoom?: number };

// FO's background fill and the City of Ann Arbor road surface are single
// polygons over the whole area. They would hide the basemap's streets, so
// they're left out and FO's detail sits on top of OSM instead.
const SKIPPED_SOURCES = new Set(["fo-20", "fo-10"]);

// A source's GeoJSON is fetched only once the map is zoomed in far enough to
// show it, and no earlier than zoom 14: the heavy layers (campus lawns 12 MB,
// sidewalks 5 MB) are only drawn up close. Until then the source holds an
// empty collection, so every layer exists from the start and FO's draw order
// holds whatever order the files arrive in.
const LOAD_FLOOR = 14;
const sourceLoadZoom = (id: string) =>
  Math.max(
    LOAD_FLOOR,
    Math.min(...(campusStyle.layers as CampusLayer[]).filter((l) => l.source === id).map((l) => l.minzoom ?? 0)),
  );

// FO's colors are drawn for a light map. On the dark basemap, flip each
// color's lightness (light lawns become dark, dark outlines become light)
// and mute its saturation, keeping the hue.
function forDark(value: unknown): unknown {
  if (typeof value === "string") {
    const m = value.match(/^rgba\((\d+), (\d+), (\d+), ([\d.]+)\)$/);
    if (!m) return value;
    const [h, s, l] = rgbToHsl(+m[1], +m[2], +m[3]);
    const [r, g, b] = hslToRgb(h, s * 0.45, 0.1 + (1 - l) * 0.55);
    return `rgba(${r}, ${g}, ${b}, ${m[4]})`;
  }
  if (Array.isArray(value)) return value.map(forDark);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, forDark(v)]));
  }
  return value;
}

function rgbToHsl(r: number, g: number, b: number): [number, number, number] {
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  const h =
    max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return [h / 6, s, l];
}

function hslToRgb(h: number, s: number, l: number): [number, number, number] {
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  const channel = (t: number) => {
    t = (t + 1) % 1;
    const c =
      t < 1 / 6 ? p + (q - p) * 6 * t : t < 1 / 2 ? q : t < 2 / 3 ? p + (q - p) * (2 / 3 - t) * 6 : p;
    return Math.round(c * 255);
  };
  return [channel(h + 1 / 3), channel(h), channel(h - 1 / 3)];
}

const EMPTY = { type: "FeatureCollection" as const, features: [] };

// Each layer's spec, ready for <Layer>, in a light and a dark version.
const LAYERS = (campusStyle.layers as CampusLayer[])
  .filter((layer) => !SKIPPED_SOURCES.has(layer.source))
  .map((layer) => {
    const { metadata: _metadata, ...spec } = layer as CampusLayer & { metadata?: unknown };
    void _metadata;
    return {
      light: spec,
      dark: { ...spec, paint: forDark(spec.paint) } as CampusLayer,
    };
  });
const SOURCES = Object.entries(campusStyle.sources).filter(([id]) => !SKIPPED_SOURCES.has(id));

// The FO source holding campus building footprints. Its features carry
// loc_ObjectNum (FO's building record number) and ObjectName.
export const FO_BUILDINGS_SOURCE = "fo-9";
export const FO_BUILDINGS_FILL = "fo-9-fill";

// U-M Facilities & Operations' campus basemap (public/campus-map/): lawns,
// sidewalks by material, buildings by type, water, athletic fields, walls,
// fences and trees, in FO's colors and draw order. Hiding it keeps the
// sources, so the building footprints stay clickable.
export function CampusDetailLayers({ theme, visible = true }: { theme: ResolvedTheme; visible?: boolean }) {
  const zoom = useMaxZoomReached();
  return (
    <>
      {SOURCES.map(([id, source]) => (
        <Source
          key={id}
          id={id}
          type="geojson"
          data={zoom >= sourceLoadZoom(id) ? source.data : EMPTY}
          attribution={source.attribution}
        >
          {LAYERS.filter(({ light }) => light.source === id).map((variants) => {
            const { source: _source, ...spec } = variants[theme];
            void _source;
            return (
              <Layer
                key={spec.id}
                {...(spec as LayerSpecification)}
                layout={{ ...spec.layout, visibility: visible ? "visible" : "none" }}
                beforeId={SLOTS.campusDetail}
              />
            );
          })}
        </Source>
      ))}
    </>
  );
}
